version: "2.1"
services:
  cassandra:
    image: cassandra:3.11.2
    ports:
      - '9042:9042'
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]